### ISSUE TITLE
Rules based on the content of files

### ISSUE THREAD

**Issue by dorongutman** [mergeability/mergeable#207]
How can I have a rule that checks the content of the diff ?
For example, fail PRs with/when:
* image tags using http:// instead of https://
* secret keys exists in code

**Comment by shine2lay** [comment]
@dorongutman It is not possible in current version. We can add this function functionality in the future versions. We will also need to update the permission to be able to read all files in order to support this feature.

**Comment by jusx** [comment]
Hi @dorongutman, we've been staying away from adding this because, in order for mergeable to validate against contents of the diff, it would need `read` access to the contents of your private repos.

This may be a problem to some teams. We are however brainstorming on supporting this in the future. 

Though, I suppose it won't be such a problem if you're running your own instance.

**Comment by dorongutman** [comment]
Hi @jusx, I understand the issue with having a read access to private repos for the hosted mergeable you offer, but if I'm serving mergeable from my own server I have no problem in it having access to that.

However, I do wish for these rules to be able to *only* check the changes of the PR and not the whole contents of the repository (meaning, the state of the repository in the commit of the PR).
For example, if I have a rule that image tags must use https:// and not http://, I only want mergeable to check this in the diff of the pull request, and not fail if the PR doesn't contain an image tag with http:// but the repository *does* contain it.
Does that make sense ?
It's a "let's improve from now on, without going over the entire code base and changing images" approach.

**Comment by jusx** [comment]
@dorongutman Makes sense.
