### ISSUE TITLE
feature request: add validator for review_requested

### ISSUE THREAD

**Issue by abid-mujtaba** [mergeability/mergeable#397]
Would be useful to trigger actions when a review has been requested by the author.

**Comment by samj1912** [comment]
This is already supported. You can validate and perform actions based on specific events. So you can make that event be pull_request.review_requested instead of pull_request.* See https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#pull_request for supported events.

**Comment by abid-mujtaba** [comment]
In that case we should introduce a *null validator* that always passes or allow for stanzas without validation.

The use case is to take an action on that event without regard to any other state.

**Comment by samj1912** [comment]
That does make sense, would you like to add a feature request for a null validator?

**Comment by abid-mujtaba** [comment]
Sure. On it.
