### ISSUE TITLE
Will add/remove PR label thousands of times when using fail/pass in the same time

### ISSUE THREAD

**Issue by zhongjiajie** [mergeability/mergeable#643]
Hi team, I have a question about my mergeable configuration. 

In DolphinScheduler, we try to add `dependent` validate to test whether PR changes database DDL simultaneously, this test will add a comment and label when the validator can not fail, and remove the label once the validator passes again. You could see a more detailed configuration in https://github.com/apache/dolphinscheduler/pull/10638/files#diff-3fb64bc6b9fe11934106ee173470a523781e604cf938226f766e104e748e1a9f.

usually, it works fine, but sometime the bot will get mad and keep trying to remove and delete the label that which maintainer add to PR, and it will do that a thousand times. I try to fix it by changing the config in https://github.com/apache/dolphinscheduler/pull/7099 but it seems that it does not work, so I finally remove all label or comment actions in https://github.com/apache/dolphinscheduler/pull/10638

You could see the add/delete label behavior in PR comment https://github.com/apache/dolphinscheduler/pull/10638#issuecomment-1167285882

**Comment by shine2lay** [comment]
@zhongjiajie I believe this behavior is occurring because of you specified `when: pull_request.*` and when a label is added to an issue, we received `pull_request.labeled` event, and does the normal flow of validating and doing `action` based on result. This unfortunately also includes when mergeable bot modify a label. Currently the way mergeable is doing labeling is by fetching existing labels, calculate new set of labels it should be and call `setLabels`. 

From your use case, I think if you remove `pull_request.labled` event, it should be okay

**Comment by shine2lay** [comment]
Alternatively I think we should check if fetched set of label is the same as new set of label and only call `setLabel` if they are different

**Comment by zhongjiajie** [comment]
After I modify according to your advice, it work well and the bad behavior not occur anymore, thanks @shine2lay and I will close this issue
